pipeline {
    agent any

    stages {
        stage('Unit tests - backend') {
            agent {
                docker {
                    image 'golang:1.21-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }   
            }
        }
    }
}
