# fly.toml app configuration file generated for bugtracker-tvb on 2025-07-07T12:59:08+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bugtracker-staging-tvb'
primary_region = 'otp'

[build.args]
  NEXT_PUBLIC_API_URL = "https://bugtracker-backend-staging-tvb.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
